name: Build and deploy ASP.Net Core app to Azure Web App - mywebhooks

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore EventGridAPIs/EventGridAPIs.csproj

      - name: Build
        run: dotnet build EventGridAPIs/EventGridAPIs.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish EventGridAPIs/EventGridAPIs.csproj --configuration Release --no-build --output ${{github.workspace}}/publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ${{github.workspace}}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./published-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mywebhooks'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_58D035DBD2724102A68DE80C024EC007 }}
          package: ./published-app
